name: swapp
description: Swapp Project

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  mobx:
  flutter_mobx:
  provider: ^2.0.0
  timeline_tile: ^0.1.2

dev_dependencies:
  mobx_codegen:
  build_runner:
  flutter_test:
    sdk: flutter
  google_fonts: ^1.1.0
  flutter_highlight: ^0.6.0

flutter:

  uses-material-design: true

  assets:
    - lib/images/joncruz.jpg
    - assets/images/image_main.png
